### ISSUE TITLE
No type generated

### ISSUE THREAD

**Issue by doubleyoudii** [mayajs/cli#7] opened 2019-12-02 06:58 UTC
## 📝 Describe the bug
Can be seen once we serve the code.

**Comment by Mackignacio** [comment] 2020-03-16 22:27
Please follow the format of creating issues. Can you reproduce your problem step by step for us to check.

**Comment by Mackignacio** [comment] 2020-03-17 10:36
Closing this issue because of not using proper issue templates.

**Closed by Mackignacio** 2020-03-17 10:36 UTC
Labels: bug
